spring:
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_book-review-db
    username: freedb_book-review
    password: AQ&3Vy7AjvxpPWa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

googlebooks:
    secret: ${GOOGLE_BOOKS_API_KEY}
